### ISSUE TITLE
If the tag property is filled, it will fail - tags[]

### ISSUE THREAD

**Issue by mossbeard** [q2g/q2g-helper-qrs-nuget#19]

**Comment by konne** [comment]
@mossbeard please describe the issue with more details

**Comment by mossbeard** [comment]
@konne Wenn das Tag array in der Klasse HubInfo gefüllt, also Tags auf Apps vergeben wurden, kommt es zu einer Fehlermeldung.
Dieses Verhalten wurde jetzt behoben.
